id: fc16ac22e757400caea795b8406169b5
initial_creation_type: ocr
source_metadata:
  volumes:
    08aa1fb445334eeaa1440e26efc7558d:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
